spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfrs_prod
    username: sfrs_prod_user
    password: ravi
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false